# Generated by Django 5.2.6 on 2025-09-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='sumitted_date',
            new_name='submitted_date',
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin_code',
            field=models.CharField(max_length=128),
        ),
    ]
