# Generated by Django 5.2.6 on 2025-10-02 09:02

import api.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=api.storage_backends.MediaStorage(), upload_to=''),
        ),
    ]
