# Generated by Django 5.2.6 on 2025-10-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin_code',
            field=models.CharField(max_length=128),
        ),
    ]
