# Generated by Django 5.2.6 on 2025-09-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_pin_supplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pin',
            old_name='attempts',
            new_name='failed_attempts',
        ),
        migrations.AddField(
            model_name='pin',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
