# Generated by Django 5.2.6 on 2025-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_attempts_pin_failed_attempts_pin_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='locked_until',
        ),
        migrations.AddField(
            model_name='pin',
            name='max_attempts',
            field=models.IntegerField(default=3),
        ),
    ]
