# Generated by Django 5.2.6 on 2025-09-19 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pin_locked_until_pin_max_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='pin',
            name='max_attempts',
        ),
    ]
